name: Sy-Update

on:
  schedule:
    - cron: '0 0 * */60'
  workflow_dispatch:

jobs:
  sync-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add upstream repository
        run: git remote add upstream https://github.com/x-dr/telegraph-Image.git

      - name: Fetch all upstream branches
        run: git fetch upstream

      - name: Checkout upstream changes excluding .github
        run: |
          git checkout upstream/master -- . 
          git reset -- .github

      - name: Clean untracked files, preserving .github directory
        run: |
          git clean -fdx -e .github
