name: Sy-Update

on:
  schedule:
    - cron: '0 0 * */60' # 每60天的UTC时间午夜执行（UTC时间）
  workflow_dispatch:

jobs:
  sync-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

# 添加上游信息
      - name: Add upstream repository
        run: git remote add upstream https://github.com/x-dr/telegraph-Image.git

#获取所有分支（若只更新指定的分支自己写）
      - name: Fetch all upstream branches
        run: git fetch upstream

# 检出上游仓库的更改并忽略.github文件夹（我是直接删除当前仓库的数据注意保留）然后更新合并   
      - name: Checkout upstream changes excluding .github
        run: |
          git checkout upstream/master -- . 
          git reset -- .github

      - name: Clean untracked files, preserving .github directory
        run: |
          git clean -fdx -e .github
